name: CI Testing with Gradle
run-name: run JUnit and Checkstyle tests with Gradle
on:
  push:
    branches:
      - master
jobs:
  JUnit-Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run ./gradlew test
        run: |
          chmod +x ./gradlew
          ./gradlew test

  Checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Checkstyle
        run: |
          chmod +x ./gradlew
          ./gradlew checkstyleMain checkstyleTest

