name: Text UI Test
run-name: Text UI Test is running on rat.Rat
on:
  push:
    branches:
      - master
    tags:
      - Level-*
jobs:
  UI-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run runtest.sh
        run: |
          chmod +x ./text-ui-test/runtest.sh
          cd ./text-ui-test
          ./runtest.sh
